### ISSUE TITLE
Autonomous selector

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2706Dashboard#3]
The labels for the autonomous modes should be easily interpreted by drive team.

Requirements:

- The dashboard should query the robot for the list of currently available autonomous modes.
- The user should be able to reorder the autonomous modes by priority.
- The dashboard should be able to send the top three prioritized autonomous modes back to the robot.

**Comment by KyleRAnderson** [comment]
Working and tested as of 3b90a90.

**Comment by georgetzavelas** [comment]
🎉
